// src/app/layout.tsx
"use client";
import "./globals.css";
import { CartProvider } from "../context/CartContext";
import { useEffect, useState } from "react";
import Footer from "@/app/components/Footer/Footer";
import Header from "@/app/components/Header/Header";
import { Bai_Jamjuree } from "next/font/google";
import CartSidebar from "@/app/components/cart/CartSidebar";

const jamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-jamjuree",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  return (
    <html lang="en" className={`${jamjuree.variable}`}>
      <body suppressHydrationWarning={!isClient}>
        <CartProvider>
          <Header />
          {children}
          <CartSidebar />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// src/app/layout.tsx
